[toolchain]

[features]
seeds = true
init-if-needed = true

[programs.devnet]
fifa_token = "11111111111111111111111111111111"

[programs.localnet]
fifa_token = "11111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
